name: Release Published

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Configure Node version and registry
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Publish to NPM
        if: ${{ !env.ACT }}
        run: echo "mock publish to npm"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#   dump-github-context:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: |
#           echo "$GITHUB_CONTEXT"


  merge-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Configure user name and email
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Merge develop branch into main
      run: |
        git fetch origin develop:develop
        git merge --no-ff develop -m "Merging develop into main via GitHub Action"

    - name: Push changes
      run: git push origin main
